"""adding message table

Revision ID: 0a5b3ec90e29
Revises: 38ea12cf8dbb
Create Date: 2025-09-03 08:55:20.753200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5b3ec90e29'
down_revision = '38ea12cf8dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('user_image_file', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('user_pkey')),
    sa.UniqueConstraint('user_email', name=op.f('user_user_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_username', name=op.f('user_user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
