"""empty message

Revision ID: 38ea12cf8dbb
Revises: 
Create Date: 2025-08-29 18:16:47.822185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ea12cf8dbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=50), nullable=False),
    sa.Column('user_first_name', sa.String(length=50), nullable=True),
    sa.Column('user_last_name', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('user_image_file', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
