"""test 3

Revision ID: 81d15a58c368
Revises: 96405f5e7e0f
Create Date: 2025-09-03 14:30:38.308817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d15a58c368'
down_revision = '96405f5e7e0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_subject', sa.String(length=100), nullable=False),
    sa.Column('message_body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('message_subject')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_username', sa.String(length=50), nullable=False),
    sa.Column('user_first_name', sa.String(length=50), nullable=True),
    sa.Column('user_last_name', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('messages')
    # ### end Alembic commands ###
