"""test 2

Revision ID: 96405f5e7e0f
Revises: f4b65a0b4595
Create Date: 2025-09-03 14:26:41.483394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96405f5e7e0f'
down_revision = 'f4b65a0b4595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    # ### end Alembic commands ###
